<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        // Usuarios
        DB::table('users')->insert([
            [
                'username' => 'admin',
                'email' => 'admin@itsn.edu.mx',
                'password' => Hash::make('admin'),
                'nombre' => 'Administrador del Sistema',
                'departamento' => 'Sistemas',
                'rol' => 'Administrador',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => 'usuario',
                'email' => 'usuario@itsn.edu.mx', 
                'password' => Hash::make('password123'),
                'nombre' => 'Usuario de Prueba',
                'departamento' => 'Recursos Humanos',
                'rol' => 'Usuario',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => '22050029',
                'email' => '22050029@itsn.edu.mx',
                'password' => Hash::make('itsn2024'),
                'nombre' => 'Estudiante ITSN',
                'departamento' => 'Estudiantes',
                'rol' => 'Usuario',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => '22050086',
                'email' => '22050086@itsn.edu.mx',
                'password' => Hash::make('itsn2024'),
                'nombre' => 'Estudiante ITSN',
                'departamento' => 'Estudiantes',
                'rol' => 'Usuario',
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);

        // Riesgos - Todos los datos del Excel
        DB::table('risks')->insert([
            [
                'lugar' => 'Edificio A, C y D',
                'actividad' => 'Actividades administrativas',
                'peligro' => 'Cortaduras por bordes filosos en vidrios de credenza en Servicios Escolares; vidrio incompleto en puestas de oficina (Centro de maestros ADM).',
                'tipo_riesgo' => 'Interno',
                'otros_factores' => 'No aplica',
                'clasificacion' => 'Seguridad',
                'tiempo_exposicion' => 1.0,
                'personas_expuestas' => 1.0,
                'probabilidad_ocurrencia' => 1.0,
                'consecuencia_infraestructura' => 1.0,
                'consecuencia_personas' => 1.0,
                'significancia' => 3.0,
                'nivel_riesgo' => 'baja',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lugar' => 'Edificio A, C y D',
                'actividad' => 'Actividades administrativas',
                'peligro' => 'Caída por cables sueltos sobre nivel de piso (Servicios escolares) o por silla con respaldo suelto o en mal estado Sala de maestros ADM',
                'tipo_riesgo' => 'Interno',
                'otros_factores' => 'No aplica',
                'clasificacion' => 'Seguridad',
                'tiempo_exposicion' => 1.0,
                'personas_expuestas' => 1.0,
                'probabilidad_ocurrencia' => 1.0,
                'consecuencia_infraestructura' => 1.0,
                'consecuencia_personas' => 1.0,
                'significancia' => 3.0,
                'nivel_riesgo' => 'baja',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lugar' => 'Todas la área',
                'actividad' => 'Mantenimiento (limpieza)',
                'peligro' => 'Resbalón y caídas por pisos mojados',
                'tipo_riesgo' => 'Interno',
                'otros_factores' => 'No aplica',
                'clasificacion' => 'Seguridad',
                'tiempo_exposicion' => 5.0,
                'personas_expuestas' => 1.0,
                'probabilidad_ocurrencia' => 1.0,
                'consecuencia_infraestructura' => 0.0,
                'consecuencia_personas' => 1.0,
                'significancia' => 6.0,
                'nivel_riesgo' => 'baja',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lugar' => 'Todas la área',
                'actividad' => 'Mantenimiento (limpieza)',
                'peligro' => 'Daño a la piel por exposición al cloro',
                'tipo_riesgo' => 'Interno',
                'otros_factores' => 'No aplica',
                'clasificacion' => 'Salud',
                'tiempo_exposicion' => 5.0,
                'personas_expuestas' => 1.0,
                'probabilidad_ocurrencia' => 1.0,
                'consecuencia_infraestructura' => 0.0,
                'consecuencia_personas' => 1.0,
                'significancia' => 6.0,
                'nivel_riesgo' => 'baja',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lugar' => 'Edificio A (planta alta) y Cafetería',
                'actividad' => 'Circulación por los pasillos',
                'peligro' => 'Golpes en la cabeza por soporte de extintor botado (el extintor ya no está)',
                'tipo_riesgo' => 'Interno',
                'otros_factores' => 'No aplica',
                'clasificacion' => 'Seguridad',
                'tiempo_exposicion' => 1.0,
                'personas_expuestas' => 1.0,
                'probabilidad_ocurrencia' => 1.0,
                'consecuencia_infraestructura' => 1.0,
                'consecuencia_personas' => 1.0,
                'significancia' => 3.0,
                'nivel_riesgo' => 'baja',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lugar' => 'Edificio A (planta alta) y Cafetería',
                'actividad' => 'Necesidades básicas',
                'peligro' => 'Caídas por goteras en sanitario de los hombre planta alta y caferería',
                'tipo_riesgo' => 'Interno',
                'otros_factores' => 'No aplica',
                'clasificacion' => 'Seguridad',
                'tiempo_exposicion' => 5.0,
                'personas_expuestas' => 3.0,
                'probabilidad_ocurrencia' => 1.0,
                'consecuencia_infraestructura' => 1.0,
                'consecuencia_personas' => 1.0,
                'significancia' => 9.0,
                'nivel_riesgo' => 'baja',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lugar' => 'Laboratorio de Química (Edificio A)',
                'actividad' => 'Prácticas de laboratorio',
                'peligro' => 'Caída por banco sin tornillo',
                'tipo_riesgo' => 'Interno',
                'otros_factores' => 'No aplica',
                'clasificacion' => 'Seguridad',
                'tiempo_exposicion' => 1.0,
                'personas_expuestas' => 2.0,
                'probabilidad_ocurrencia' => 1.0,
                'consecuencia_infraestructura' => 0.0,
                'consecuencia_personas' => 1.0,
                'significancia' => 3.0,
                'nivel_riesgo' => 'baja',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lugar' => 'Laboratorio de Química (Edificio A)',
                'actividad' => 'Prácticas de laboratorio',
                'peligro' => 'Posible electrocución por contacto suelto en escritorio del profesor',
                'tipo_riesgo' => 'Interno',
                'otros_factores' => 'No aplica',
                'clasificacion' => 'Seguridad',
                'tiempo_exposicion' => 5.0,
                'personas_expuestas' => 2.0,
                'probabilidad_ocurrencia' => 1.0,
                'consecuencia_infraestructura' => 1.0,
                'consecuencia_personas' => 1.0,
                'significancia' => 8.0,
                'nivel_riesgo' => 'baja',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lugar' => 'Edificios A, B, C Y D (aulas)',
                'actividad' => 'Impartición de clases',
                'peligro' => 'Caída por hueco en piso al final del salón (A9) y junto al escritorio (A10), por bultos de arena y ladrillos (Lab. Arq)',
                'tipo_riesgo' => 'Interno',
                'otros_factores' => 'No aplica',
                'clasificacion' => 'Seguridad',
                'tiempo_exposicion' => 5.0,
                'personas_expuestas' => 3.0,
                'probabilidad_ocurrencia' => 1.0,
                'consecuencia_infraestructura' => 1.0,
                'consecuencia_personas' => 1.0,
                'significancia' => 9.0,
                'nivel_riesgo' => 'baja',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lugar' => 'Edificios A, B, C Y D (aulas)',
                'actividad' => 'Impartición de clases',
                'peligro' => 'Caída por: butacas sin remache (A1, A3, A11), butaca inestable por pata (A3), silla con respaldo/asiento suelto (A2, A4, C4, C6, C7 y C9)',
                'tipo_riesgo' => 'Interno',
                'otros_factores' => 'No aplica',
                'clasificacion' => 'Seguridad',
                'tiempo_exposicion' => 5.0,
                'personas_expuestas' => 3.0,
                'probabilidad_ocurrencia' => 1.0,
                'consecuencia_infraestructura' => 1.0,
                'consecuencia_personas' => 1.0,
                'significancia' => 9.0,
                'nivel_riesgo' => 'baja',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lugar' => 'Edificios A, B, C Y D (aulas)',
                'actividad' => 'Impartición de clases',
                'peligro' => 'Posibles contacto eléctrico por apagador con cables expuestos (A2)',
                'tipo_riesgo' => 'Interno',
                'otros_factores' => 'No aplica',
                'clasificacion' => 'Seguridad',
                'tiempo_exposicion' => 5.0,
                'personas_expuestas' => 2.0,
                'probabilidad_ocurrencia' => 1.0,
                'consecuencia_infraestructura' => 1.0,
                'consecuencia_personas' => 1.0,
                'significancia' => 8.0,
                'nivel_riesgo' => 'baja',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lugar' => 'Edificios A, B, C Y D (aulas)',
                'actividad' => 'Impartición de clases',
                'peligro' => 'Cortaduras por bordes filosos en tubo de la silla de escritorio (A1), corte por bordes filosos en chapas de las puertas (aulas C2 y C3); por rebabas en marco de puerta (aula C8).',
                'tipo_riesgo' => 'Interno',
                'otros_factores' => 'No aplica',
                'clasificacion' => 'Seguridad',
                'tiempo_exposicion' => 1.0,
                'personas_expuestas' => 2.0,
                'probabilidad_ocurrencia' => 1.0,
                'consecuencia_infraestructura' => 1.0,
                'consecuencia_personas' => 1.0,
                'significancia' => 4.0,
                'nivel_riesgo' => 'baja',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lugar' => 'Edificios A, B, C Y D (aulas)',
                'actividad' => 'Impartición de clases',
                'peligro' => 'Toques o electrocución por contactos flojos y expuesto al interperie (Aulas C4, C6, C9, estacionamiento de vehiculos oficiales y almacen de IIAS',
                'tipo_riesgo' => 'Interno',
                'otros_factores' => 'No aplica',
                'clasificacion' => 'Seguridad',
                'tiempo_exposicion' => 5.0,
                'personas_expuestas' => 3.0,
                'probabilidad_ocurrencia' => 1.0,
                'consecuencia_infraestructura' => 1.0,
                'consecuencia_personas' => 1.0,
                'significancia' => 9.0,
                'nivel_riesgo' => 'baja',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lugar' => 'Edificios A, B, C Y D (aulas)',
                'actividad' => 'Impartición de clases',
                'peligro' => 'Golpes por plafones sueltos en las aula, oficinas administrativas y sanitarios.',
                'tipo_riesgo' => 'Interno',
                'otros_factores' => 'No aplica',
                'clasificacion' => 'Seguridad',
                'tiempo_exposicion' => 1.0,
                'personas_expuestas' => 2.0,
                'probabilidad_ocurrencia' => 1.0,
                'consecuencia_infraestructura' => 1.0,
                'consecuencia_personas' => 1.0,
                'significancia' => 4.0,
                'nivel_riesgo' => 'baja',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lugar' => 'Edificio C',
                'actividad' => 'Circulación por áreas comunes',
                'peligro' => 'Caida por Falta de Protección en escaleras para subir y bajar a 2do. Y 3er. Piso del edificio C',
                'tipo_riesgo' => 'Interno',
                'otros_factores' => 'No aplica',
                'clasificacion' => 'Seguridad',
                'tiempo_exposicion' => 5.0,
                'personas_expuestas' => 3.0,
                'probabilidad_ocurrencia' => 3.0,
                'consecuencia_infraestructura' => 1.0,
                'consecuencia_personas' => 1.0,
                'significancia' => 15.0,
                'nivel_riesgo' => 'baja',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lugar' => 'Bodegas de Edificio B',
                'actividad' => 'Mantenimiento y almacen',
                'peligro' => 'Poco control de acceso a Áreas Restringidas en: bodega de mantenimiento, almacen de semillas (IIAS) y ADIE',
                'tipo_riesgo' => 'Interno',
                'otros_factores' => 'No aplica',
                'clasificacion' => 'Seguridad',
                'tiempo_exposicion' => 1.0,
                'personas_expuestas' => 2.0,
                'probabilidad_ocurrencia' => 1.0,
                'consecuencia_infraestructura' => 0.0,
                'consecuencia_personas' => 1.0,
                'significancia' => 3.0,
                'nivel_riesgo' => 'baja',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lugar' => 'Bodegas de Edificio B',
                'actividad' => 'Mantenimiento y almacen',
                'peligro' => 'Caídas por desorden de cajas, carpetas, cables.',
                'tipo_riesgo' => 'Interno',
                'otros_factores' => 'No aplica',
                'clasificacion' => 'Seguridad',
                'tiempo_exposicion' => 1.0,
                'personas_expuestas' => 2.0,
                'probabilidad_ocurrencia' => 1.0,
                'consecuencia_infraestructura' => 0.0,
                'consecuencia_personas' => 1.0,
                'significancia' => 3.0,
                'nivel_riesgo' => 'baja',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lugar' => 'Bodegas de Edificio B',
                'actividad' => 'Mantenimiento y almacen',
                'peligro' => 'Productos y liquidos sin señalizar o identificación',
                'tipo_riesgo' => 'Interno',
                'otros_factores' => 'No aplica',
                'clasificacion' => 'Seguridad',
                'tiempo_exposicion' => 1.0,
                'personas_expuestas' => 1.0,
                'probabilidad_ocurrencia' => 1.0,
                'consecuencia_infraestructura' => 1.0,
                'consecuencia_personas' => 1.0,
                'significancia' => 3.0,
                'nivel_riesgo' => 'baja',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lugar' => 'Estacionamiento',
                'actividad' => 'Circulación de vehiculos y peatones',
                'peligro' => 'Caida, raspones, golpes, por tapa de registro de drenaje levantada. Tapa en mal estado, expuesta a caída.',
                'tipo_riesgo' => 'Interno',
                'otros_factores' => 'No aplica',
                'clasificacion' => 'Seguridad',
                'tiempo_exposicion' => 5.0,
                'personas_expuestas' => 3.0,
                'probabilidad_ocurrencia' => 1.0,
                'consecuencia_infraestructura' => 1.0,
                'consecuencia_personas' => 1.0,
                'significancia' => 9.0,
                'nivel_riesgo' => 'baja',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lugar' => 'Estacionamiento',
                'actividad' => 'Circulación de vehiculos y peatones',
                'peligro' => 'Tropiezos o golpes por motocicletas estacionadas en área de acceso entre los edificios C y D y en el estacionamiento de vehiculos oficiales.',
                'tipo_riesgo' => 'Interno',
                'otros_factores' => 'No aplica',
                'clasificacion' => 'Seguridad',
                'tiempo_exposicion' => 5.0,
                'personas_expuestas' => 3.0,
                'probabilidad_ocurrencia' => 3.0,
                'consecuencia_infraestructura' => 0.0,
                'consecuencia_personas' => 1.0,
                'significancia' => 12.0,
                'nivel_riesgo' => 'baja',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lugar' => 'Áreas exteriores/pasillos.',
                'actividad' => 'Circulación por áreas comunes',
                'peligro' => 'Posible picadura de araña. Nido de araña capulina (viuda negra) en bancas de pasillos y mobiliario de las aulas',
                'tipo_riesgo' => 'Interno',
                'otros_factores' => 'No aplica',
                'clasificacion' => 'Seguridad',
                'tiempo_exposicion' => 1.0,
                'personas_expuestas' => 4.0,
                'probabilidad_ocurrencia' => 1.0,
                'consecuencia_infraestructura' => 1.0,
                'consecuencia_personas' => 1.0,
                'significancia' => 6.0,
                'nivel_riesgo' => 'baja',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lugar' => 'Áreas exteriores/pasillos.',
                'actividad' => 'Circulación por áreas comunes',
                'peligro' => 'Panales de avispas',
                'tipo_riesgo' => 'Interno',
                'otros_factores' => 'No aplica',
                'clasificacion' => 'Seguridad',
                'tiempo_exposicion' => 5.0,
                'personas_expuestas' => 3.0,
                'probabilidad_ocurrencia' => 3.0,
                'consecuencia_infraestructura' => 1.0,
                'consecuencia_personas' => 1.0,
                'significancia' => 15.0,
                'nivel_riesgo' => 'baja',
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);

        // Requisitos legales de ejemplo
        DB::table('legal_requirements')->insert([
            [
                'norma' => 'ISO 45001:2018',
                'titulo' => 'Contexto de la organización',
                'tipo_requisito' => 'Requisito General',
                'numero_requisito' => '4.1',
                'descripcion' => 'La organización debe determinar las cuestiones externas e internas que son pertinentes para su propósito y que afectan a su capacidad para lograr los resultados previstos de su SST.',
                'cumplimiento' => 'si',
                'evidencia' => 'Documento de análisis del contexto',
                'acciones_no' => null,
                'peligro_asociado' => 'Falta de identificación de riesgos externos',
                'fecha_cumplimiento' => '2024-01-15',
                'responsables' => 'Dirección General',
                'frecuencia_control' => 'Anual',
                'responsable_control' => 'Responsable SGI',
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);

        // Notificaciones de ejemplo
        DB::table('notifications')->insert([
            [
                'titulo' => 'Actualización del Sistema',
                'descripcion' => 'El sistema de gestión de seguridad ha sido actualizado a la versión 2.1.',
                'tipo' => 'info',
                'estado' => 'no_leida',
                'remitente' => 'Administrador',
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);
    }
}