<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        // Usuarios
        DB::table('users')->insert([
            [
                'username' => 'admin',
                'email' => 'admin@itsn.edu.mx',
                'password' => Hash::make('admin'),
                'nombre' => 'Administrador del Sistema',
                'departamento' => 'Sistemas',
                'rol' => 'Administrador',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => 'usuario',
                'email' => 'usuario@itsn.edu.mx', 
                'password' => Hash::make('password123'),
                'nombre' => 'Usuario de Prueba',
                'departamento' => 'Recursos Humanos',
                'rol' => 'Usuario',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => '22050029',
                'email' => '22050029@itsn.edu.mx',
                'password' => Hash::make('itsn2024'),
                'nombre' => 'Estudiante ITSN',
                'departamento' => 'Estudiantes',
                'rol' => 'Usuario',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => '22050086',
                'email' => '22050086@itsn.edu.mx',
                'password' => Hash::make('itsn2024'),
                'nombre' => 'Estudiante ITSN',
                'departamento' => 'Estudiantes',
                'rol' => 'Usuario',
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);

        // Riesgos - Todos los datos del Excel
        DB::table('risks')->insert([
            [
                'lugar' => 'Edificio A, C y D',
                'actividad' => 'Actividades administrativas',
                'peligro' => 'Cortaduras por bordes filosos en vidrios de credenza en Servicios Escolares; vidrio incompleto en puestas de oficina (Centro de maestros ADM).',
                'tipo_riesgo' => 'Interno',
                'otros_factores' => 'No aplica',
                'clasificacion' => 'Seguridad',
                'tiempo_exposicion' => 1.0,
                'personas_expuestas' => 1.0,
                'probabilidad_ocurrencia' => 1.0,
                'consecuencia_infraestructura' => 1.0,
                'consecuencia_personas' => 1.0,
                'significancia' => 6.0,
                'nivel_riesgo' => 'baja',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lugar' => 'Edificio A, C y D',
                'actividad' => 'Actividades administrativas',
                'peligro' => 'Caída por cables sueltos sobre nivel de piso (Servicios escolares) o por silla con respaldo suelto o en mal estado Sala de maestros ADM',
                'tipo_riesgo' => 'Interno',
                'otros_factores' => 'No aplica',
                'clasificacion' => 'Seguridad',
                'tiempo_exposicion' => 1.0,
                'personas_expuestas' => 1.0,
                'probabilidad_ocurrencia' => 1.0,
                'consecuencia_infraestructura' => 1.0,
                'consecuencia_personas' => 1.0,
                'significancia' => 6.0,
                'nivel_riesgo' => 'baja',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lugar' => 'Todas la área',
                'actividad' => 'Mantenimiento (limpieza)',
                'peligro' => 'Resbalón y caídas por pisos mojados',
                'tipo_riesgo' => 'Interno',
                'otros_factores' => 'No aplica',
                'clasificacion' => 'Seguridad',
                'tiempo_exposicion' => 5.0,
                'personas_expuestas' => 1.0,
                'probabilidad_ocurrencia' => 1.0,
                'consecuencia_infraestructura' => 0.0,
                'consecuencia_personas' => 1.0,
                'significancia' => 7.0,
                'nivel_riesgo' => 'baja',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lugar' => 'Todas la área',
                'actividad' => 'Mantenimiento (limpieza)',
                'peligro' => 'Daño a la piel por exposición al cloro',
                'tipo_riesgo' => 'Interno',
                'otros_factores' => 'No aplica',
                'clasificacion' => 'Salud',
                'tiempo_exposicion' => 5.0,
                'personas_expuestas' => 1.0,
                'probabilidad_ocurrencia' => 1.0,
                'consecuencia_infraestructura' => 0.0,
                'consecuencia_personas' => 1.0,
                'significancia' => 7.0,
                'nivel_riesgo' => 'baja',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lugar' => 'Edificio A (planta alta) y Cafetería',
                'actividad' => 'Circulación por los pasillos',
                'peligro' => 'Golpes en la cabeza por soporte de extintor botado (el extintor ya no está)',
                'tipo_riesgo' => 'Interno',
                'otros_factores' => 'No aplica',
                'clasificacion' => 'Seguridad',
                'tiempo_exposicion' => 1.0,
                'personas_expuestas' => 1.0,
                'probabilidad_ocurrencia' => 1.0,
                'consecuencia_infraestructura' => 1.0,
                'consecuencia_personas' => 1.0,
                'significancia' => 6.0,
                'nivel_riesgo' => 'baja',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lugar' => 'Edificio A (planta alta) y Cafetería',
                'actividad' => 'Necesidades básicas',
                'peligro' => 'Caídas por goteras en sanitario de los hombre planta alta y caferería',
                'tipo_riesgo' => 'Interno',
                'otros_factores' => 'No aplica',
                'clasificacion' => 'Seguridad',
                'tiempo_exposicion' => 5.0,
                'personas_expuestas' => 3.0,
                'probabilidad_ocurrencia' => 1.0,
                'consecuencia_infraestructura' => 1.0,
                'consecuencia_personas' => 1.0,
                'significancia' => 18.0,
                'nivel_riesgo' => 'baja',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lugar' => 'Laboratorio de Química (Edificio A)',
                'actividad' => 'Prácticas de laboratorio',
                'peligro' => 'Caída por banco sin tornillo',
                'tipo_riesgo' => 'Interno',
                'otros_factores' => 'No aplica',
                'clasificacion' => 'Seguridad',
                'tiempo_exposicion' => 1.0,
                'personas_expuestas' => 2.0,
                'probabilidad_ocurrencia' => 1.0,
                'consecuencia_infraestructura' => 0.0,
                'consecuencia_personas' => 1.0,
                'significancia' => 4.0,
                'nivel_riesgo' => 'baja',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lugar' => 'Laboratorio de Química (Edificio A)',
                'actividad' => 'Prácticas de laboratorio',
                'peligro' => 'Posible electrocución por contacto suelto en escritorio del profesor',
                'tipo_riesgo' => 'Interno',
                'otros_factores' => 'No aplica',
                'clasificacion' => 'Seguridad',
                'tiempo_exposicion' => 5.0,
                'personas_expuestas' => 2.0,
                'probabilidad_ocurrencia' => 1.0,
                'consecuencia_infraestructura' => 1.0,
                'consecuencia_personas' => 1.0,
                'significancia' => 16.0,
                'nivel_riesgo' => 'baja',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lugar' => 'Edificios A, B, C Y D (aulas)',
                'actividad' => 'Impartición de clases',
                'peligro' => 'Caída por hueco en piso al final del salón (A9) y junto al escritorio (A10), por bultos de arena y ladrillos (Lab. Arq)',
                'tipo_riesgo' => 'Interno',
                'otros_factores' => 'No aplica',
                'clasificacion' => 'Seguridad',
                'tiempo_exposicion' => 5.0,
                'personas_expuestas' => 3.0,
                'probabilidad_ocurrencia' => 1.0,
                'consecuencia_infraestructura' => 1.0,
                'consecuencia_personas' => 1.0,
                'significancia' => 18.0,
                'nivel_riesgo' => 'baja',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lugar' => 'Edificios A, B, C Y D (aulas)',
                'actividad' => 'Impartición de clases',
                'peligro' => 'Caída por: butacas sin remache (A1, A3, A11), butaca inestable por pata (A3), silla con respaldo/asiento suelto (A2, A4, C4, C6, C7 y C9)',
                'tipo_riesgo' => 'Interno',
                'otros_factores' => 'No aplica',
                'clasificacion' => 'Seguridad',
                'tiempo_exposicion' => 5.0,
                'personas_expuestas' => 3.0,
                'probabilidad_ocurrencia' => 1.0,
                'consecuencia_infraestructura' => 1.0,
                'consecuencia_personas' => 1.0,
                'significancia' => 18.0,
                'nivel_riesgo' => 'baja',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lugar' => 'Edificios A, B, C Y D (aulas)',
                'actividad' => 'Impartición de clases',
                'peligro' => 'Posibles contacto eléctrico por apagador con cables expuestos (A2)',
                'tipo_riesgo' => 'Interno',
                'otros_factores' => 'No aplica',
                'clasificacion' => 'Seguridad',
                'tiempo_exposicion' => 5.0,
                'personas_expuestas' => 2.0,
                'probabilidad_ocurrencia' => 1.0,
                'consecuencia_infraestructura' => 1.0,
                'consecuencia_personas' => 1.0,
                'significancia' => 16.0,
                'nivel_riesgo' => 'baja',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lugar' => 'Edificios A, B, C Y D (aulas)',
                'actividad' => 'Impartición de clases',
                'peligro' => 'Cortaduras por bordes filosos en tubo de la silla de escritorio (A1), corte por bordes filosos en chapas de las puertas (aulas C2 y C3); por rebabas en marco de puerta (aula C8).',
                'tipo_riesgo' => 'Interno',
                'otros_factores' => 'No aplica',
                'clasificacion' => 'Seguridad',
                'tiempo_exposicion' => 1.0,
                'personas_expuestas' => 2.0,
                'probabilidad_ocurrencia' => 1.0,
                'consecuencia_infraestructura' => 1.0,
                'consecuencia_personas' => 1.0,
                'significancia' => 8.0,
                'nivel_riesgo' => 'baja',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lugar' => 'Edificios A, B, C Y D (aulas)',
                'actividad' => 'Impartición de clases',
                'peligro' => 'Toques o electrocución por contactos flojos y expuesto al interperie (Aulas C4, C6, C9, estacionamiento de vehiculos oficiales y almacen de IIAS',
                'tipo_riesgo' => 'Interno',
                'otros_factores' => 'No aplica',
                'clasificacion' => 'Seguridad',
                'tiempo_exposicion' => 5.0,
                'personas_expuestas' => 3.0,
                'probabilidad_ocurrencia' => 1.0,
                'consecuencia_infraestructura' => 1.0,
                'consecuencia_personas' => 1.0,
                'significancia' => 18.0,
                'nivel_riesgo' => 'baja',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lugar' => 'Edificios A, B, C Y D (aulas)',
                'actividad' => 'Impartición de clases',
                'peligro' => 'Golpes por plafones sueltos en las aula, oficinas administrativas y sanitarios.',
                'tipo_riesgo' => 'Interno',
                'otros_factores' => 'No aplica',
                'clasificacion' => 'Seguridad',
                'tiempo_exposicion' => 1.0,
                'personas_expuestas' => 2.0,
                'probabilidad_ocurrencia' => 1.0,
                'consecuencia_infraestructura' => 1.0,
                'consecuencia_personas' => 1.0,
                'significancia' => 8.0,
                'nivel_riesgo' => 'baja',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lugar' => 'Edificio C',
                'actividad' => 'Circulación por áreas comunes',
                'peligro' => 'Caida por Falta de Protección en escaleras para subir y bajar a 2do. Y 3er. Piso del edificio C',
                'tipo_riesgo' => 'Interno',
                'otros_factores' => 'No aplica',
                'clasificacion' => 'Seguridad',
                'tiempo_exposicion' => 5.0,
                'personas_expuestas' => 3.0,
                'probabilidad_ocurrencia' => 3.0,
                'consecuencia_infraestructura' => 1.0,
                'consecuencia_personas' => 1.0,
                'significancia' => 22.0,
                'nivel_riesgo' => 'baja',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lugar' => 'Bodegas de Edificio B',
                'actividad' => 'Mantenimiento y almacen',
                'peligro' => 'Poco control de acceso a Áreas Restringidas en: bodega de mantenimiento, almacen de semillas (IIAS) y ADIE',
                'tipo_riesgo' => 'Interno',
                'otros_factores' => 'No aplica',
                'clasificacion' => 'Seguridad',
                'tiempo_exposicion' => 1.0,
                'personas_expuestas' => 2.0,
                'probabilidad_ocurrencia' => 1.0,
                'consecuencia_infraestructura' => 0.0,
                'consecuencia_personas' => 1.0,
                'significancia' => 4.0,
                'nivel_riesgo' => 'baja',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lugar' => 'Bodegas de Edificio B',
                'actividad' => 'Mantenimiento y almacen',
                'peligro' => 'Caídas por desorden de cajas, carpetas, cables.',
                'tipo_riesgo' => 'Interno',
                'otros_factores' => 'No aplica',
                'clasificacion' => 'Seguridad',
                'tiempo_exposicion' => 1.0,
                'personas_expuestas' => 2.0,
                'probabilidad_ocurrencia' => 1.0,
                'consecuencia_infraestructura' => 0.0,
                'consecuencia_personas' => 1.0,
                'significancia' => 4.0,
                'nivel_riesgo' => 'baja',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lugar' => 'Bodegas de Edificio B',
                'actividad' => 'Mantenimiento y almacen',
                'peligro' => 'Productos y liquidos sin señalizar o identificación',
                'tipo_riesgo' => 'Interno',
                'otros_factores' => 'No aplica',
                'clasificacion' => 'Seguridad',
                'tiempo_exposicion' => 1.0,
                'personas_expuestas' => 1.0,
                'probabilidad_ocurrencia' => 1.0,
                'consecuencia_infraestructura' => 1.0,
                'consecuencia_personas' => 1.0,
                'significancia' => 6.0,
                'nivel_riesgo' => 'baja',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lugar' => 'Estacionamiento',
                'actividad' => 'Circulación de vehiculos y peatones',
                'peligro' => 'Caida, raspones, golpes, por tapa de registro de drenaje levantada. Tapa en mal estado, expuesta a caída.',
                'tipo_riesgo' => 'Interno',
                'otros_factores' => 'No aplica',
                'clasificacion' => 'Seguridad',
                'tiempo_exposicion' => 5.0,
                'personas_expuestas' => 3.0,
                'probabilidad_ocurrencia' => 1.0,
                'consecuencia_infraestructura' => 1.0,
                'consecuencia_personas' => 1.0,
                'significancia' => 18.0,
                'nivel_riesgo' => 'baja',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lugar' => 'Estacionamiento',
                'actividad' => 'Circulación de vehiculos y peatones',
                'peligro' => 'Tropiezos o golpes por motocicletas estacionadas en área de acceso entre los edificios C y D y en el estacionamiento de vehiculos oficiales.',
                'tipo_riesgo' => 'Interno',
                'otros_factores' => 'No aplica',
                'clasificacion' => 'Seguridad',
                'tiempo_exposicion' => 5.0,
                'personas_expuestas' => 3.0,
                'probabilidad_ocurrencia' => 3.0,
                'consecuencia_infraestructura' => 0.0,
                'consecuencia_personas' => 1.0,
                'significancia' => 11.0,
                'nivel_riesgo' => 'baja',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lugar' => 'Áreas exteriores/pasillos.',
                'actividad' => 'Circulación por áreas comunes',
                'peligro' => 'Posible picadura de araña. Nido de araña capulina (viuda negra) en bancas de pasillos y mobiliario de las aulas',
                'tipo_riesgo' => 'Interno',
                'otros_factores' => 'No aplica',
                'clasificacion' => 'Seguridad',
                'tiempo_exposicion' => 1.0,
                'personas_expuestas' => 4.0,
                'probabilidad_ocurrencia' => 1.0,
                'consecuencia_infraestructura' => 1.0,
                'consecuencia_personas' => 1.0,
                'significancia' => 12.0,
                'nivel_riesgo' => 'baja',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lugar' => 'Áreas exteriores/pasillos.',
                'actividad' => 'Circulación por áreas comunes',
                'peligro' => 'Panales de avispas',
                'tipo_riesgo' => 'Interno',
                'otros_factores' => 'No aplica',
                'clasificacion' => 'Seguridad',
                'tiempo_exposicion' => 5.0,
                'personas_expuestas' => 3.0,
                'probabilidad_ocurrencia' => 3.0,
                'consecuencia_infraestructura' => 1.0,
                'consecuencia_personas' => 1.0,
                'significancia' => 22.0,
                'nivel_riesgo' => 'baja',
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);

        // Requisitos legales de ejemplo
        DB::table('legal_requirements')->insert([
            [
                'norma' => 'NOM-001-STPS-2008',
                'categoria_norma' => 'seguridad',
                'titulo' => 'EDIFICIOS, LOCALES, INSTALACIONES Y AREAS EN LOS CENTROS DE TRABAJO - CONDICIONES DE SEGURIDAD',
                'tipo_requisito' => 'MEDIDAS DE SEGURIDAD',
                'numero_requisito' => '5.1',
                'descripcion' => 'Conservar en condiciones seguras las instalaciones de los centros de trabajo, para que no representen riesgos.',
                'cumplimiento' => 'no',
                'evidencia' => null,
                'acciones_no' => '- Colocación de jaladera en credenza.                             
                - Colocación de canaletas en cables sueltos.                            
                - Mantenimiento de mobiliario.',
                'peligro_asociado' => '- Cortaduras por bordes filosos en vidrios de credenza en Servicios Escolares; vidrio incompleto en puestas de oficina (Centro de maestros ADM) y vidrios sueltos sin protección (Edificio D-ARQ)                                                                                                                        
                - Caída por cables sueltos sobre nivel de piso (Servicios escolares). 
                - Problemas respiratorios por humedad. 
                - Mobiliario en mal estado (bancos, butacas, sillas) en las aulas.',
                'fecha_cumplimiento' => '2025-10-01',
                'responsables' => 'Recursos Materiales',
                'frecuencia_control' => 'Semestral',
                'responsable_control' => 'Comision Mixta de Seguridad',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'norma' => 'NOM-011-STPS-2001',
                'categoria_norma' => 'salud',
                'titulo' => 'CONDICIONES DE SEGURIDAD E HIGIENE EN LOS CENTROS DE TRABAJO DONDE SE GENERE RUIDO.',
                'tipo_requisito' => 'RECONOCIMIENTO, EVALUACIÓN Y CONTROL',
                'numero_requisito' => '5.2',
                'descripcion' => 'Contar con el reconocimiento y evaluación de todas las áreas del centro de trabajo donde haya
                trabajadores y cuyo NSA sea igual o superior a 80 dB(A), incluyendo sus características y componentes de
                frecuencia, conforme a lo establecido en los apéndices B y C.',
                'cumplimiento' => null,
                'evidencia' => null,
                'acciones_no' => null,
                'peligro_asociado' => null,
                'fecha_cumplimiento' => null,
                'responsables' => null,
                'frecuencia_control' => null,
                'responsable_control' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'norma' => 'NOM-017-STPS-2008',
                'categoria_norma' => 'organizacion',
                'titulo' => 'EQUIPO DE PROTECCIÓN PERSONAL-SELECCIÓN, USO Y MANEJO EN LOS CENTROS DE TRABAJO.',
                'tipo_requisito' => 'ESTUDIOS, REGISTROS ADMINISTRATIVOS',
                'numero_requisito' => '5.2',
                'descripcion' => ' Identificar y analizar los riesgos de trabajo a los que están expuestos los trabajadores 
                por cada puesto de trabajo y área del centro laboral. Esta información debe registrarse y conservarse 
                actualizada mientras no se modifiquen los implementos y procesos de trabajo, con al menos los siguientes datos: 
                tipo de actividad que desarrolla el trabajador, tipo de riesgo de trabajo identificado, 
                región anatómica por proteger, puesto de trabajo y equipo de protección personal requerido.',
                'cumplimiento' => null,
                'evidencia' => null,
                'acciones_no' => null,
                'peligro_asociado' => null,
                'fecha_cumplimiento' => null,
                'responsables' => null,
                'frecuencia_control' => null,
                'responsable_control' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);
    }
}